[NetInfo]
#NetDiscoverType:网络发现方式  1=通过UDP组播进行网络发现 2=与中心结点连接进行网络发现 3=通过代理服务
#NetDiscoverType=2
#LocalIP=110.8.8.41

#当NetDiscoverType设为1：通过UDP组播进行网络发现时该组参数才有效，此时参数必填
MulticastIP=228.8.8.8
MulticastPort=18888

#当NetDiscoverType设为2：与中心结点连接进行网络发现时该组参数才有效，此时参数必填
CenterNodeIP=127.0.0.1
CenterNodePort=19999

#当NetDiscoverType设为3：通过代理服务进行网络发现时该组参数才有效，此时参数必填
#与HostProxy代理服务的m_pInXSubSocket绑定的端口相同, 不冲突的话不要改
PubSocketPort=16666
#与HostProxy代理服务的m_pInXPubSocket绑定的端口相同, 不冲突的话不要改
SubSocketPort=16667
